<div class="containerFooter">

    <footer class="row" rel="stylesheet">

        <div class="row">
            <div class="col">
                <ul>
                    <li class="col-xs-6 col-sm-2">
                        <a href="https://www.facebook.com/fogtraelastbyggecenter/">
                            <img class="logo"
                                 src="https://cdn2.iconfinder.com/data/icons/black-white-social-media/32/online_social_media_facebook-128.png">
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col">
                <ul>
                    <li class="col-xs-6 col-sm-2">
                        <a href="https://www.instagram.com/fogtraelastbyggecenter/">
                            <img class="logo"
                                 src="https://cdn2.iconfinder.com/data/icons/black-white-social-media/32/instagram_online_social_media_photo-128.png">
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col">
                <ul>
                    <h4>Adresse: </h4>
                <a href="https://www.google.dk/maps/place/N%C3%B8rgaardsvej+3,+2800+Kongens+Lyngby/@55.7702008,12.5048934,17z/data=!3m1!4b1!4m5!3m4!1s0x46524e6cf23ef2e1:0x5fe7d19f27285031!8m2!3d55.7702008!4d12.5070821">
                    <h6>Noergaardsvej 3, 2800 Lyngby</h6>
                    </a>
                </ul>
            </div>
            <div class="col">
                            <ul>
                                <h4>Telefon: </h4>
                                <h6>+45 45 26 63 00</h6>

                            </ul>
                        </div>
                        <div class="col">
                                        <ul>
                                            <h4>Email: </h4>
                                           <a href="mailto:info@johannesfog.dk" target="_top">
                                            <h6>info@johannesfog.dk</h6>
                                            </a>
                                        </ul>
                                    </div>
        </div>


    </footer>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</div>
</body>
</html>