
<div class="containerFooter">

    <footer class="row" rel="stylesheet">
        <div class="sozial col-xs-12 col-sm-6 col-sm-push-6">

            <ul class="row">
                <li class="col-xs-6 col-sm-2">
                    <a href="#">
                        <img class="logo"
                             src="https://cdn2.iconfinder.com/data/icons/black-white-social-media/32/online_social_media_facebook-128.png">
                    </a>
                </li>
                <li class="col-xs-6 col-sm-2">
                    <a href="#">
                        <img class="logo"
                             src="https://cdn2.iconfinder.com/data/icons/black-white-social-media/32/twitter_online_social_media-128.png">
                    </a>
                </li>
                <li class="col-xs-6 col-sm-2">
                    <a href="#">
                        <img class="logo"
                             src="https://cdn2.iconfinder.com/data/icons/black-white-social-media/32/instagram_online_social_media_photo-128.png">
                    </a>
                </li>
                <li class="col-xs-6 col-sm-2">
                    <a href="#">
                        <img class="logo"
                             src="https://cdn2.iconfinder.com/data/icons/black-white-social-media/32/online_social_media_google_plus-128.png">
                    </a>
                </li>
            </ul>
        </div>
        

        <div class="copyright col-xs-12 col-sm-3 col-sm-pull-6">
            <p> &copy; Me from now to eternity </p>
        </div>

        <div class="impressum col-xs-12 col-sm-3 col-sm-pull-6">
            <p> An impressive impressum </p>
            <p> Adresse und so </p>
        </div>
    </footer>



<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

      </body>
</html>